[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "totalite-scoring-pipeline-proto"
version = "0.1.0"
description = "Prototype for Totalite scoring pipeline"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "Totalite Team"}
]

dependencies = [
    "pydantic-settings>=2.10.0",
    "streamlit>=1.47.0",
    "sqlalchemy>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "pandas>=2.0.0",
    "plotly>=6.2.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.12.0",
    "mypy>=1.8.0",
    "pandas-stubs>=2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.ruff]
target-version = "py311"
line-length = 88

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true
ignore_missing_imports = true 